title: "Xiang Wan's Homepage"

author: "Sean Wan"
description: "Last Update: 06/23/2022"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout
show_social: true         # show footer
show_excerpts: false       # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header

# Menu
navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "research.md"}
  #- {url: "/katie.pdf", title: "CV"}
  - {title: "Teaching", file: "teaching.md"}
  - {title: "Research", file: "research.md"}



remote_theme: niklasbuschmann/contrast@v2.11

plugins:
  - jekyll-remote-theme
  - jekyll-feed

