# Dependencies
gems:                [jekyll-paginate]
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Hyde
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://xiangwanmath.github.io/
baseurl:          https://xiangwanmath.github.io/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         2

# Custom vars
Last update:          06/23/2022



#plugins: [jekyll-paginate]