url: "https://xiangwanmath.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. /blog

title: "Xiang Wan"
#subtitle: "Departmant of Mathematics and Statistics, Loyola University Chicago"

#author: "..."
description: "Last Update: 01/01/2024."
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout
show_social: true         # show footer
show_excerpts: false       # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header

# Menu
navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: "Home", file: "index.md"}
  - {title: "Research", file: "research_summary.md"}
  - {title: "Teaching", file: "teaching_summary.md"}
  - {title: "SIAM Student Chapter", file: "SIAM_Chapter.md"}
  - {title: "Miscellaneous", file: "miscellaneous.md"}
  # - {url: "/CV.pdf", title: "CV"}
  # - {title: "another1", file: "another1.md"}

# external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  # - {title: Mail, icon: envelope, url: "mailto:niklasbuschmann@users.noreply.github.com"}
  # - {title: Github, icon: github, url: "https://github.com/niklasbuschmann/contrast"}
  # - {title: Subscribe, icon: rss, url: "/feed.xml"}



remote_theme: niklasbuschmann/contrast@v2.11

plugins:
  - jekyll-remote-theme
  - jekyll-feed

